# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

theme: blowfish
baseURL: https://web.gartenacker.de/m/
defaultContentLanguage: de

# pluralizeListTitles = "true" # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles

enableRobotsTXT: true
summaryLength: 0

buildDrafts: true
buildFuture: true

enableEmoji: true
publishDir: /var/www/html/m

# googleAnalytics = "G-XXXXXXXXX"

pagination:
  pagerSize: 10
  
imaging:
  anchor: Center
  
taxonomies:
  rubrik: rubriken
  reiseziel: reiseziele
  gegend: gegenden
  sportart: sportarten
  region: regionen
  thema: themen
  gericht: gerichte
  author: authors
  
sitemap:
  changefreq: daily
  filename: sitemap.xml
  priority: 0.5
  
outputs:
  home:
    - HTML
    - RSS
    - JSON
    
related:
  threshold: 0
  toLower: false
  indices:
    - name: rubriken
      weight: 100
    - name: reiseziele
      weight: 100
    - name: gegenden
      weight: 100
    - name: sportarten
      weight: 100
    - name: regionen
      weight: 100
    - name: themen
      weight: 100
    - name: gerichte
      weight: 100
    - applyFilter: false
      name: fragmentrefs
      type: fragments
      weight: 10
